import { Footer, Navbar } from "@/components";
import "./globals.css";
import ConfigureRedux from "@/redux/ConfigureRedux";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="desktop:w-full w-[1440px]"
        suppressHydrationWarning={true}
      >
        <ConfigureRedux>
          <Navbar />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </ConfigureRedux>
      </body>
    </html>
  );
}
